import Foundation

extension OAPI.Models.TestData {
    typealias ClanProfile = OAPI.Models.ClanProfile
    
    static let clanProfile =
        ClanProfile(tag: String("#PUULJY"),
                    name: String("PERSIAN"),
                    type: String("inviteOnly"),
                    description: String("new persian clan , welcome کاپ پایین کیک میشه"),
                    badgeId: Int(16000122),
                    badgeName: String("Fugi03"),
                    clanScore: Int(4055),
                    clanWarTrophies: Int(20904),
                    location: ClanProfile.Location(id: Int(57000115),
                    name: String("Iran"),
                    isCountry: Bool(true),
                    countryCode: String("IR")),
                    requiredTrophies: Int(5600),
                    donationsPerWeek: Int(0),
                    clanChestStatus: String("inactive"),
                    clanChestLevel: Int(1),
                    clanChestMaxLevel: Int(0),
                    members: Int(2),
                    memberList: [ClanProfile.Member(tag: String("#8PLJVGV"),
                    name: String("BEHROUZ"),
                    role: String("coLeader"),
                    lastSeen: String("20200618T032706.000Z"),
                    expLevel: Int(13),
                    trophies: Int(4062),
                    arena: ClanProfile.Arena(id: Int(54000012),
                    name: String("Legendary Arena")),
                    clanRank: Int(1),
                    previousClanRank: Int(1),
                    donations: Int(0),
                    donationsReceived: Int(0),
                    clanChestPoints: Int(0)),
                    ClanProfile.Member(tag: String("#20UGJJV"),
                    name: String("Lucifer"),
                    role: String("leader"),
                    lastSeen: String("20200728T065125.000Z"),
                    expLevel: Int(12),
                    trophies: Int(4048),
                    arena: ClanProfile.Arena(id: Int(54000012),
                    name: String("Legendary Arena")),
                    clanRank: Int(2),
                    previousClanRank: Int(2),
                    donations: Int(0),
                    donationsReceived: Int(0),
                    clanChestPoints: Int(0))])
}
