import Foundation

extension OAPI.Models.TestData {
    typealias PlayerBattle = OAPI.Models.PlayerBattle
    
    static let playerBattles = [
        PlayerBattle(type: ("PvP"),
                     challengeTitle: (""),
                     title: ("Ladder"),
                     battleTime: ("20200729T062824.000Z"),
                     isLadderTournament: (false),
                     arena: (PlayerBattle.Arena(id: (54000045),
                                                name: ("Shipwreck Island"))),
                     gameMode: (PlayerBattle.GameMode(id: (72000006),
                                                      name: ("Ladder"))),
                     deckSelection: ("collection"),
                     team: (
                        [PlayerBattle.Battler(tag: ("#8V0Q8R2L"),
                                              name: ("<OMEGA> TOKYO"),
                                              startingTrophies: (5797),
                                              kingTowerHitPoints: (1296),
                                              princessTowersHitPoints: ([0,
                                                                         0]),
                                              trophyChange: (-27),
                                              crowns: (1),
                                              clan: (PlayerBattle.Clan(tag: ("#9PJ82CRC"),
                                                                       name: ("RoyaleAPI Alpha"),
                                                                       badgeId: (16000005),
                                                                       badgeName: ("Sword_02"))),
                                              cards: ([PlayerBattle.Card(name: ("Skeletons"),
                                                                         id: (26000010),
                                                                         oldLevel: (13),
                                                                         level: (13),
                                                                         maxLevel: (13),
                                                                         starLevel: (1),
                                                                         enumValue: (DataSet.Cards.skeletons),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/oO7iKMU5m0cdxhYPZA3nWQiAUh2yoGgdThLWB1rVSec.png")))),
                                                       PlayerBattle.Card(name: ("Royal Delivery"),
                                                                         id: (28000018),
                                                                         oldLevel: (13),
                                                                         level: (13),
                                                                         maxLevel: (13),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.royalDelivery),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/LPg7AGjGI3_xmi7gLLgGC50yKM1jJ2teWkZfoHJcIZo.png")))),
                                                       PlayerBattle.Card(name: ("Balloon"),
                                                                         id: (26000006),
                                                                         oldLevel: (8),
                                                                         level: (13),
                                                                         maxLevel: (8),
                                                                         starLevel: (3),
                                                                         enumValue: (DataSet.Cards.balloon),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/qBipxLo-3hhCnPrApp2Nn3b2NgrSrvwzWytvREev0CY.png")))),
                                                       PlayerBattle.Card(name: ("Hunter"),
                                                                         id: (26000044),
                                                                         oldLevel: (8),
                                                                         level: (13),
                                                                         maxLevel: (8),
                                                                         starLevel: (3),
                                                                         enumValue: (DataSet.Cards.hunter),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/VNabB1WKnYtYRSG7X_FZfnZjQDHTBs9A96OGMFmecrA.png")))),
                                                       PlayerBattle.Card(name: ("The Log"),
                                                                         id: (28000011),
                                                                         oldLevel: (5),
                                                                         level: (13),
                                                                         maxLevel: (5),
                                                                         starLevel: (1),
                                                                         enumValue: (DataSet.Cards.theLog),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/_iDwuDLexHPFZ_x4_a0eP-rxCS6vwWgTs6DLauwwoaY.png")))),
                                                       PlayerBattle.Card(name: ("Giant Snowball"),
                                                                         id: (28000017),
                                                                         oldLevel: (13),
                                                                         level: (13),
                                                                         maxLevel: (13),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.giantSnowball),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/7MaJLa6hK9WN2_VIshuh5DIDfGwm0wEv98gXtAxLDPs.png")))),
                                                       PlayerBattle.Card(name: ("Miner"),
                                                                         id: (26000032),
                                                                         oldLevel: (5),
                                                                         level: (13),
                                                                         maxLevel: (5),
                                                                         starLevel: (2),
                                                                         enumValue: (DataSet.Cards.miner),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/Y4yWvdwBCg2FpAZgs8T09Gy34WOwpLZW-ttL52Ae8NE.png")))),
                                                       PlayerBattle.Card(name: ("Ice Golem"),
                                                                         id: (26000038),
                                                                         oldLevel: (11),
                                                                         level: (13),
                                                                         maxLevel: (11),
                                                                         starLevel: (1),
                                                                         enumValue: (DataSet.Cards.iceGolem),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/r05cmpwV1o7i7FHodtZwW3fmjbXCW34IJCsDEV5cZC4.png"))))]))]),
                     opponent: (
                        [PlayerBattle.Battler(tag: ("#22YG2VV8"),
                                              name: ("D ICE R"),
                                              startingTrophies: (5800),
                                              kingTowerHitPoints: (5832),
                                              princessTowersHitPoints: ([260,
                                                                         0]),
                                              trophyChange: (29),
                                              crowns: (2),
                                              clan: (PlayerBattle.Clan(tag: ("#YGP2CGV"),
                                                                       name: ("Aus CastleBlack"),
                                                                       badgeId: (16000028),
                                                                       badgeName: ("Skull_05"))),
                                              cards: ([PlayerBattle.Card(name: ("Bats"),
                                                                         id: (26000049),
                                                                         oldLevel: (13),
                                                                         level: (13),
                                                                         maxLevel: (13),
                                                                         starLevel: (2),
                                                                         enumValue: (DataSet.Cards.bats),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/EnIcvO21hxiNpoI-zO6MDjLmzwPbq8Z4JPo2OKoVUjU.png")))),
                                                       PlayerBattle.Card(name: ("Wall Breakers"),
                                                                         id: (26000058),
                                                                         oldLevel: (8),
                                                                         level: (13),
                                                                         maxLevel: (8),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.wallBreakers),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/_xPphEfC8eEwFNrfU3cMQG9-f5JaLQ31ARCA7l3XtW4.png")))),
                                                       PlayerBattle.Card(name: ("Bandit"),
                                                                         id: (26000046),
                                                                         oldLevel: (5),
                                                                         level: (13),
                                                                         maxLevel: (5),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.bandit),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/QWDdXMKJNpv0go-HYaWQWP6p8uIOHjqn-zX7G0p3DyM.png")))),
                                                       PlayerBattle.Card(name: ("Miner"),
                                                                         id: (26000032),
                                                                         oldLevel: (5),
                                                                         level: (13),
                                                                         maxLevel: (5),
                                                                         starLevel: (2),
                                                                         enumValue: (DataSet.Cards.miner),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/Y4yWvdwBCg2FpAZgs8T09Gy34WOwpLZW-ttL52Ae8NE.png")))),
                                                       PlayerBattle.Card(name: ("Musketeer"),
                                                                         id: (26000014),
                                                                         oldLevel: (11),
                                                                         level: (13),
                                                                         maxLevel: (11),
                                                                         starLevel: (1),
                                                                         enumValue: (DataSet.Cards.musketeer),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/Tex1C48UTq9FKtAX-3tzG0FJmc9jzncUZG3bb5Vf-Ds.png")))),
                                                       PlayerBattle.Card(name: ("Mega Knight"),
                                                                         id: (26000055),
                                                                         oldLevel: (5),
                                                                         level: (13),
                                                                         maxLevel: (5),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.megaKnight),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/O2NycChSNhn_UK9nqBXUhhC_lILkiANzPuJjtjoz0CE.png")))),
                                                       PlayerBattle.Card(name: ("Zap"),
                                                                         id: (28000008),
                                                                         oldLevel: (13),
                                                                         level: (13),
                                                                         maxLevel: (13),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.zap),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/7dxh2-yCBy1x44GrBaL29vjqnEEeJXHEAlsi5g6D1eY.png")))),
                                                       PlayerBattle.Card(name: ("Barbarian Barrel"),
                                                                         id: (28000015),
                                                                         oldLevel: (8),
                                                                         level: (13),
                                                                         maxLevel: (8),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.barbarianBarrel),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/Gb0G1yNy0i5cIGUHin8uoFWxqntNtRPhY_jeMXg7HnA.png"))))]))])),
        PlayerBattle(type: ("PvP"),
                     challengeTitle: (""),
                     title: ("Ladder"),
                     battleTime: ("20200729T062125.000Z"),
                     isLadderTournament: (false),
                     arena: (PlayerBattle.Arena(id: (54000045),
                                                name: ("Shipwreck Island"))),
                     gameMode: (PlayerBattle.GameMode(id: (72000006),
                                                      name: ("Ladder"))),
                     deckSelection: ("collection"),
                     team: (
                        [PlayerBattle.Battler(tag: ("#8V0Q8R2L"),
                                              name: ("<OMEGA> TOKYO"),
                                              startingTrophies: (5823),
                                              kingTowerHitPoints: (2388),
                                              princessTowersHitPoints: ([0,
                                                                         0]),
                                              trophyChange: (-26),
                                              crowns: (1),
                                              clan: (PlayerBattle.Clan(tag: ("#9PJ82CRC"),
                                                                       name: ("RoyaleAPI Alpha"),
                                                                       badgeId: (16000005),
                                                                       badgeName: ("Sword_02"))),
                                              cards: ([PlayerBattle.Card(name: ("Skeletons"),
                                                                         id: (26000010),
                                                                         oldLevel: (13),
                                                                         level: (13),
                                                                         maxLevel: (13),
                                                                         starLevel: (1),
                                                                         enumValue: (DataSet.Cards.skeletons),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/oO7iKMU5m0cdxhYPZA3nWQiAUh2yoGgdThLWB1rVSec.png")))),
                                                       PlayerBattle.Card(name: ("Royal Delivery"),
                                                                         id: (28000018),
                                                                         oldLevel: (13),
                                                                         level: (13),
                                                                         maxLevel: (13),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.royalDelivery),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/LPg7AGjGI3_xmi7gLLgGC50yKM1jJ2teWkZfoHJcIZo.png")))),
                                                       PlayerBattle.Card(name: ("Balloon"),
                                                                         id: (26000006),
                                                                         oldLevel: (8),
                                                                         level: (13),
                                                                         maxLevel: (8),
                                                                         starLevel: (3),
                                                                         enumValue: (DataSet.Cards.balloon),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/qBipxLo-3hhCnPrApp2Nn3b2NgrSrvwzWytvREev0CY.png")))),
                                                       PlayerBattle.Card(name: ("Hunter"),
                                                                         id: (26000044),
                                                                         oldLevel: (8),
                                                                         level: (13),
                                                                         maxLevel: (8),
                                                                         starLevel: (3),
                                                                         enumValue: (DataSet.Cards.hunter),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/VNabB1WKnYtYRSG7X_FZfnZjQDHTBs9A96OGMFmecrA.png")))),
                                                       PlayerBattle.Card(name: ("The Log"),
                                                                         id: (28000011),
                                                                         oldLevel: (5),
                                                                         level: (13),
                                                                         maxLevel: (5),
                                                                         starLevel: (1),
                                                                         enumValue: (DataSet.Cards.theLog),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/_iDwuDLexHPFZ_x4_a0eP-rxCS6vwWgTs6DLauwwoaY.png")))),
                                                       PlayerBattle.Card(name: ("Giant Snowball"),
                                                                         id: (28000017),
                                                                         oldLevel: (13),
                                                                         level: (13),
                                                                         maxLevel: (13),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.giantSnowball),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/7MaJLa6hK9WN2_VIshuh5DIDfGwm0wEv98gXtAxLDPs.png")))),
                                                       PlayerBattle.Card(name: ("Miner"),
                                                                         id: (26000032),
                                                                         oldLevel: (5),
                                                                         level: (13),
                                                                         maxLevel: (5),
                                                                         starLevel: (2),
                                                                         enumValue: (DataSet.Cards.miner),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/Y4yWvdwBCg2FpAZgs8T09Gy34WOwpLZW-ttL52Ae8NE.png")))),
                                                       PlayerBattle.Card(name: ("Ice Golem"),
                                                                         id: (26000038),
                                                                         oldLevel: (11),
                                                                         level: (13),
                                                                         maxLevel: (11),
                                                                         starLevel: (1),
                                                                         enumValue: (DataSet.Cards.iceGolem),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/r05cmpwV1o7i7FHodtZwW3fmjbXCW34IJCsDEV5cZC4.png"))))]))]),
                     opponent: (
                        [PlayerBattle.Battler(tag: ("#PJ008PYLQ"),
                                              name: ("junior09"),
                                              startingTrophies: (5842),
                                              kingTowerHitPoints: (3479),
                                              princessTowersHitPoints: ([1559,
                                                                         0]),
                                              trophyChange: (28),
                                              crowns: (2),
                                              clan: (PlayerBattle.Clan(tag: ("#PP0RGUUV"),
                                                                       name: ("Cr culichi"),
                                                                       badgeId: (16000154),
                                                                       badgeName: ("A_Char_Goblin_01"))),
                                              cards: ([PlayerBattle.Card(name: ("Balloon"),
                                                                         id: (26000006),
                                                                         oldLevel: (8),
                                                                         level: (13),
                                                                         maxLevel: (8),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.balloon),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/qBipxLo-3hhCnPrApp2Nn3b2NgrSrvwzWytvREev0CY.png")))),
                                                       PlayerBattle.Card(name: ("Wizard"),
                                                                         id: (26000017),
                                                                         oldLevel: (11),
                                                                         level: (13),
                                                                         maxLevel: (11),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.wizard),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/Mej7vnv4H_3p_8qPs_N6_GKahy6HDr7pU7i9eTHS84U.png")))),
                                                       PlayerBattle.Card(name: ("Minions"),
                                                                         id: (26000005),
                                                                         oldLevel: (13),
                                                                         level: (13),
                                                                         maxLevel: (13),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.minions),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/yHGpoEnmUWPGV_hBbhn-Kk-Bs838OjGzWzJJlQpQKQA.png")))),
                                                       PlayerBattle.Card(name: ("Battle Ram"),
                                                                         id: (26000036),
                                                                         oldLevel: (11),
                                                                         level: (13),
                                                                         maxLevel: (11),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.battleRam),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/dyc50V2cplKi4H7pq1B3I36pl_sEH5DQrNHboS_dbbM.png")))),
                                                       PlayerBattle.Card(name: ("Rage"),
                                                                         id: (28000002),
                                                                         oldLevel: (8),
                                                                         level: (13),
                                                                         maxLevel: (8),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.rage),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/bGP21OOmcpHMJ5ZA79bHVV2D-NzPtDkvBskCNJb7pg0.png")))),
                                                       PlayerBattle.Card(name: ("The Log"),
                                                                         id: (28000011),
                                                                         oldLevel: (5),
                                                                         level: (13),
                                                                         maxLevel: (5),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.theLog),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/_iDwuDLexHPFZ_x4_a0eP-rxCS6vwWgTs6DLauwwoaY.png")))),
                                                       PlayerBattle.Card(name: ("Hunter"),
                                                                         id: (26000044),
                                                                         oldLevel: (8),
                                                                         level: (13),
                                                                         maxLevel: (8),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.hunter),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/VNabB1WKnYtYRSG7X_FZfnZjQDHTBs9A96OGMFmecrA.png")))),
                                                       PlayerBattle.Card(name: ("Skeleton Army"),
                                                                         id: (26000012),
                                                                         oldLevel: (7),
                                                                         level: (12),
                                                                         maxLevel: (8),
                                                                         starLevel: (0),
                                                                         enumValue: (DataSet.Cards.skeletonArmy),
                                                                         iconUrls: (PlayerBattle.IconUrls(medium: ("https://api-assets.clashroyale.com/cards/300/fAOToOi1pRy7svN2xQS6mDkhQw2pj9m_17FauaNqyl4.png"))))]))]))]
}
